// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRcLetLB9VGvheBq2RA-OITTXbsJR7ll8',
    appId: '1:494547887935:web:683a7c18517edfa79cd58a',
    messagingSenderId: '494547887935',
    projectId: 'fashion-app-lab4',
    authDomain: 'fashion-app-lab4.firebaseapp.com',
    storageBucket: 'fashion-app-lab4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCSP4U2mfw1pWxH1MypJG2lXuk80pHXdg',
    appId: '1:494547887935:android:7aab6a3a74604cdd9cd58a',
    messagingSenderId: '494547887935',
    projectId: 'fashion-app-lab4',
    storageBucket: 'fashion-app-lab4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDirTHENFajwLoitvCIiM4BTnss67K50rA',
    appId: '1:494547887935:ios:36ecf8d86dbaead39cd58a',
    messagingSenderId: '494547887935',
    projectId: 'fashion-app-lab4',
    storageBucket: 'fashion-app-lab4.firebasestorage.app',
    iosBundleId: 'com.example.lab3Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDirTHENFajwLoitvCIiM4BTnss67K50rA',
    appId: '1:494547887935:ios:36ecf8d86dbaead39cd58a',
    messagingSenderId: '494547887935',
    projectId: 'fashion-app-lab4',
    storageBucket: 'fashion-app-lab4.firebasestorage.app',
    iosBundleId: 'com.example.lab3Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRcLetLB9VGvheBq2RA-OITTXbsJR7ll8',
    appId: '1:494547887935:web:150e5db858851c5a9cd58a',
    messagingSenderId: '494547887935',
    projectId: 'fashion-app-lab4',
    authDomain: 'fashion-app-lab4.firebaseapp.com',
    storageBucket: 'fashion-app-lab4.firebasestorage.app',
  );
}
